IDSps1/Controllers/DonorController.cs
using IDSps1.Data;
using IDSps1.Models;
using Microsoft.AspNetCore.Mvc;

namespace IDSps1.Controllers
{
    public class DonorController : Controller
    {
        private readonly ApplicationDbContext _database;

        public DonorController(ApplicationDbContext db)
        {
            _database = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Charity> objcharity = _database.Charity;
            return View(objcharity);
        }

        public IActionResult Payment()
        {
            return View();
        }
    }
}

IDSps1/Controllers/NGOController.cs
using IDSps1.Data;
using IDSps1.Models;
using Microsoft.AspNetCore.Mvc;

namespace IDSps1.Controllers
{
    public class NGOController : Controller
    {
       
        private readonly ApplicationDbContext _db;

        public NGOController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Review> objReviews = _db.Reviews;
            return View(objReviews);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Requirements,Link")] Review Reviews)
        {
            if (ModelState.IsValid)
            {
                _db.Add(Reviews);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Reviews);
        }
    }
}

IDSps1/Controllers/charitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IDSps1.Data;
using IDSps1.Models;
using Microsoft.AspNetCore.Authorization;

namespace IDSps1.Controllers
{
    public class charitiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public charitiesController(ApplicationDbContext context)
        {
            _context = context;
        }

       
        // GET: charities
        public async Task<IActionResult> Index()
        {
              return _context.Charity != null ? 
                          View(await _context.Charity.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.charity'  is null.");
        }
        [Authorize]
        // GET: charity/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();        
        }

        // POST: charity/ShowSearchResults
        [Authorize]
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.Charity.Where( j => j.NGO.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: charities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Charity == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charity == null)
            {
                return NotFound();
            }

            return View(charity);
        }

        // GET: charities/Create
        
        public IActionResult Create()
        {
            return View();
        }

        // POST: charities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NGO,Requirements")] Charity charity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(charity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(charity);
        }

        // GET: charities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Charity == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity.FindAsync(id);
            if (charity == null)
            {
                return NotFound();
            }
            return View(charity);
        }

        // POST: charities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NGO,Requirements")] Charity charity)
        {
            if (id != charity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(charity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!charityExists(charity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(charity);
        }

       

        // GET: charities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Charity == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charity == null)
            {
                return NotFound();
            }

            return View(charity);
        }

        // POST: charities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Charity == null)
            {
                return Problem("Entity set 'ApplicationDbContext.charity'  is null.");
            }
            var charity = await _context.Charity.FindAsync(id);
            if (charity != null)
            {
                _context.Charity.Remove(charity);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool charityExists(int id)
        {
          return (_context.Charity?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

IDSps1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IDSps1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IDSps1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IDSps1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="charities" asp-action="Index">Charity</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Donor" asp-action="Index">Donate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NGO" asp-action="Index">NGO</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IDSps1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>